apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server-mul
  labels:
    name: iperf3-server-mul
  namespace: gedge-default
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "multus-static2",
              "ips": [ "10.255.2.50/24" ]
            }
    ]'
spec:
  nodeName: etri-worker2
  containers:
  - name: iperf3-server-mul
    image: 10.10.0.104:5000/iperf3
    command: ["iperf3", "-s"]
