apiVersion: v1
kind: Pod
metadata:
  name: iperf-client
  labels:
    name: iperf-client
  namespace: gedge-default
spec:
  nodeName: etri-worker1
  containers:
  - name: iperf-client
    image: 10.10.0.104:5000/net_test
    command: 
    - /root/iperf-test.sh
    args: ["10.10.0.101"]
