apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
  labels:
    name: iperf3-server
  namespace: gedge-default
spec:
  nodeName: etri-worker2
  containers:
  - name: iperf3-server
    image: 10.10.0.104:5000/iperf3
    command: ["iperf3", "-s"]
