apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-sriov
  labels:
    name: iperf-client-sriov
  namespace: gedge-default
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        { "name": "sriov-static2",
          "ips": [ "10.10.3.54/24" ]
        }
      ]'
spec:
  nodeName: etri-worker1
  containers:
  - name: iperf-client-sriov
    image: 10.10.0.104:5000/net_test
    command:
    - /root/iperf-test.sh
    args: ["10.10.3.50"]
