apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server-sriov
  labels:
    name: iperf3-server-sriov
  namespace: gedge-default
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "sriov-static2",
              "ips": [ "10.10.3.50/24" ]
            }
    ]'
spec:
  nodeName: etri-worker1
  containers:
  - name: iperf3-server-sriov
    image: 10.10.0.104:5000/iperf3
    command: ["iperf3", "-s"]
